spring:
  application:
    name: sprboot_devel

# 비밀번호 8자 대소문자 특문 필수!!!!!!!!!!
  datasource:
    url: jdbc:mysql://localhost:3306/shop_db?serverTimezone=Asia/Seoul
    username: root
    password: Abcd123@
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  port: 8088

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: me.shinsunyoung.domain
